# baseurl = "http://replace-this-with-your-hugo-site.com/"
baseurl = "/"
# 相対パスを有効にする
# canonifyurls = true
# languageCode = "en-us"
languageCode = "ja"
# 日本語でSummaryを正しく表示する
hasCJKLanguage = true
# title = "My New Hugo Site"
title = "Your Site Name"

[params]
#  disqusShortname = "your disqus id." # optional
#  highlight = true # optional
