# baseurl = "http://replace-this-with-your-hugo-site.com/"
baseurl = "/"
# 相対パスを有効にする
# canonifyurls = true
# languageCode = "en-us"
languageCode = "ja"
# 日本語でSummaryを正しく表示する
hasCJKLanguage = true
# title = "My New Hugo Site"
title = "Your Site Name"
# googleAnalytics = "UA-00000000-9"

[params]
paginate = 3
#  copyright = "Copyright (c) 2008 - 2014, Steve Francia; all rights reserved."
#  disqusShortname = "your disqus id." # optional
#  highlight = true # optional
latestPostsNum = 5 # optional
