# baseurl = "http://replace-this-with-your-hugo-site.com/"
baseurl = "/"
# 相対パスを有効にする
# canonifyurls = true
# languageCode = "en-us"
languageCode = "ja"
# title = "My New Hugo Site"
title = "Your Site Name"

